#!/usr/bin/python

def build(bld):
  bld.shlib(
    source = [
      'topiclm.cpp',
      'unigram_rescaling.cpp',
      'context_tree.cpp',
      'context_tree_manager.cpp',
      'context_tree_analyzer.cpp',
      'lambda_manager.cpp',
      'restaurant_manager.cpp',
      'parameters.cpp',
      'dirichlet_sampler.cpp',
      'hpy_sampler.cpp',
      'document_manager.cpp',
      'particle_filter_document_manager.cpp',
      'particle_filter_sampler.cpp',
      'restaurant.cpp',
      'random_util.cpp',
      'section_table_seq.cpp',
      'child_table_selector.cpp',
      'floor_sampler.cpp',
      'node_util.cpp',
      'table_based_sampler.cpp'
      ],
    target = 'topiclm',
    name = 'TOPICLM',
    includes    = '.',
    use = 'pficommon_data pficommon_text pficommon_system')

  bld.program(
    source = 'topiclm_train.cpp',
    target = 'topiclm_train',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'topiclm_predict.cpp',
    target = 'topiclm_predict',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'unigram_rescaling_train.cpp',
    target = 'unigram_rescaling_train',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'unigram_rescaling_predict.cpp',
    target = 'unigram_rescaling_predict',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'dirichlet_sampler_test.cpp',
    target = 'dirichlet_sampler_test',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'analyze_model.cpp',
    target = 'analyze_model',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    source = 'log_probability.cpp',
    target = 'log_probability',
    includes = '.',
    use = 'TOPICLM')
  bld.program(
    features = 'gtest',
    source = 'floor_sampler_test.cpp',
    target = 'floor_sampler_test',
    includes = '.',
    use = 'TOPICLM')

